### ISSUE TITLE
k key events do not show up in terminal

### ISSUE THREAD

**Issue by thejayvm** [Floobits/atom-term3#1]
Mac OS X 10.10.5
Atom 1.0.18
term3 0.11.0

Whenever I type any sort of key combination with the letter `K` it does not register in the terminal. Even just on it's own.

So `rake db:migrate` ends up being `rae db:migrate` and there's no real way of getting the k into the terminal.

I get no errors when this happens.

**Comment by kans** [comment]
Wow!  somehow, I have not noticed this?  Or maybe its just your "k"?  I will take a closer look.

**Comment by thejayvm** [comment]
Ha... my k does show up in other terminals :)

A similar thing was happening in the last functioning build of term2. Every time I hit `k` I'd get the `isMac` error. Except the `k` would still show up. I'm not sure the two are related - but I wouldn't be surprised.

**Comment by kans** [comment]
Ok, I can not type the letter k either!

**Comment by kans** [comment]
OK,

We tracked down the bug to this upstream [pr](https://github.com/f/atom-term.js/pull/3/files#diff-ae1c69a2029d04e8fdf4f1a13bc241f2R2527)

```javascript
case 75:
  if ((!isMac && ev.ctrlKey) || (isMac && ev.metaKey)) {
    this.clear();
    return cancel(ev);
  }
// F1
case 112:
  key = '\x1bOP';
```

I don't think this code every worked - isMac is undefined (missing this) and the case falls through in the general case to F1!

The plan is submit a PR upstream and to fork atom-term.js and link against it in the mean time.
