### ISSUE TITLE
Failed to update and multiple terminal sessions 

### ISSUE THREAD

**Issue by Opligitory** [Floobits/atom-term3#12]
when i tried to update my version if term3 0.19.0 to term3 0.19.2 it gave me an error 

> pty.js@0.3.0 install /private/var/folders/hc/d4w12_x9283g3n10_5jn7zp40000gr/T/apm-install-dir-115930-7228-viffc8/node_modules/term3/node_modules/pty.js
node-gyp rebuild

*npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated*

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/hc/d4w12_x9283g3n10_5jn7zp40000gr/T/apm-install-dir-115930-7228-viffc8/node_modules/term3/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/MYUSER/.atom/.apm/.apmrc" "--userconfig" "/Users/MYUSER/.atom/.apmrc" "install" "/private/var/folders/hc/d4w12_x9283g3n10_5jn7zp40000gr/T/d-115930-7228-19z4z66/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/hc/d4w12_x9283g3n10_5jn7zp40000gr/T/apm-install-dir-115930-7228-viffc8/npm-debug.log
>
and after this every time i attempted to create a new terminal  session multiple new terminals would start at the same time

**Comment by ggreer** [comment]
I don't want to be derisive, but did you read the error message you pasted? Run Xcode and agree to the license. Everything will work after that.
