### ISSUE TITLE
Background uses theme style background and that can be undesirable

### ISSUE THREAD

**Issue by AddictArts** [Floobits/atom-term3#13]
Simple fix is in term-view.coffee applyStyle, by commenting out commented line where it sets it to null
```
# remove background color in favor of the atom background
#@term.element.style.background = null
```

![yuck](https://cloud.githubusercontent.com/assets/911906/10925553/0a023b4c-8244-11e5-8926-c37311d45a54.png)
vs
![better](https://cloud.githubusercontent.com/assets/911906/10925560/0dbc60f0-8244-11e5-9b63-d4d8011c168f.png)

**Comment by liudangyi** [comment]
:+1:

**Comment by johnnyjian** [comment]
+1

**Comment by ggreer** [comment]
OK, new release pushed. I'm still not sure this will fix styling issues for everyone, though.
