### ISSUE TITLE
Conflicting with `dotenv` module on variable `NODE_ENV`

### ISSUE THREAD

**Issue by verdywid** [Floobits/atom-term3#31]
I am working on node project which uses `motdotla/dotenv` module to customise my environment module. However it seems this plugin already set the `NODE_ENV` environment variable to `production` which explains why my `.env` doesn't work anymore

`dotenv` will ignore any environment variable that's already set because It works fine if I run my project directly through terminal.

**Comment by ggreer** [comment]
I don't think there's anything we can do for this. Atom is setting NODE_ENV, not term3.

**Comment by jgog** [comment]
Even if Atom is setting it, can we populate/override it when opening term3?

**Comment by ggreer** [comment]
Un-setting environment variables is a great way to cause even more problems.

It seems to me that if you want an environment variable set to a value, you should set it to that value. Lots of things could set `NODE_ENV` or other environment variables used by verdywid's scripts. That whole setup sounds very brittle.
