### ISSUE TITLE
How change the default shell?

### ISSUE THREAD

**Issue by fcomrqz** [Floobits/atom-term3#49]
By default open with bash but I want use zsh. I am using OS X.

How can I make the switch for default?

Thank you for your help.

**Comment by ggreer** [comment]
Packages → Term3 → Settings, then scroll down to Shell Override and enter the absolute path to your shell.

Though if you used `chsh` to set your user shell, we should obey that. Did you manually change your shell in Terminal.app or something? I use zsh and term3 works correctly without anything in Shell Override.

**Comment by fcomrqz** [comment]
Thank for your answer bro. But I resolved with changing the user _Login shell._

![change shell](https://cloud.githubusercontent.com/assets/1501123/14622452/9c49fa3e-058f-11e6-8366-d0998bfd42d3.png)

**Comment by nixpulvis** [comment]
This doesn't seem to work with `fish`.

**Comment by sebma** [comment]
@fcomrqz I'm using MacOS Sierra. Where is your screen shot coming from ? System Preferences->Users & Groups ?
I don't have an "Advanced Options" window here, strange

**Comment by fcomrqz** [comment]
Hello @sebma my screenshot is from System Preferences → Users & Groups → Right click on my user → Advanced options 😅
![2017-06-05 at 9 36 am](https://cloud.githubusercontent.com/assets/1501123/26788358/89bcc346-49d2-11e7-8b95-3b201628b229.png)

**Comment by sebma** [comment]
Thanks, these setting were well hidden :)
