### ISSUE TITLE
cannot install correctly

### ISSUE THREAD

**Issue by canfoderiskii** [Floobits/atom-term3#53]
Atom Version: 1.7.2

I just tried to install atom-term3 package from Setting-install page, but failed.

What should i do to solve this problem or do some workarounds..

Here is the error output:

>\> ptyw.js@0.3.7 install C:\Users\Geminii\AppData\Local\Temp\apm-install-dir-116320-11100-1o7t34a\node_modules\term3\node_modules\ptyw.js
>\> node-gyp rebuild
>C:\Users\Geminii\AppData\Local\Temp\apm-install-dir-116320-11100-1o7t34a\node_modules\term3\node_modules\ptyw.js>if not defined npm_config_node_gyp (node "D:\Green software\Atom\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
>npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Green software\\Atom\\resources\\app\\apm\\bin\\node.exe" "D:\\Green software\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "D:\\Green software\\Atom\\.atom\\.apm\\.apmrc" "--userconfig" "D:\\Green software\\Atom\\.atom\\.apmrc" "install" "C:\\Users\\Geminii\\AppData\\Local\\Temp\\d-116320-11100-7eah1i\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
>npm ERR! ptyw.js@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ptyw.js@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.

**Comment by MichaelIT** [comment]
## I am using mac osx 10.11.4 , Atom 1.72 , I got some errors too.
## I trying install atom-term3 and atom atom-term2,all install faild!
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/michael/.atom/.apm/.apmrc" "--userconfig" "/Users/michael/.atom/.apmrc" "install" "/private/var/folders/46/m90w174917j3z7_sgy3jsb8h0000gn/T/d-116321-13979-jxbquj/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ptyw.js@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/46/m90w174917j3z7_sgy3jsb8h0000gn/T/apm-install-dir-116321-13979-1ltzqee/npm-debug.log

**Comment by canfoderiskii** [comment]
In my error output, is this argument "--arch=ia32" correct?
My computer cpu is i7-4700. The architecture is x86 not ia32.

So, does the "--arch=ia32" indicate more or less error source?

**Comment by Vrakfall** [comment]
+1

**Comment by MatthiasF999** [comment]
Gyp requires Python 2.7 and Visual Studio 2013.
Visual Studio 2015 won't work, since one of the commands uses `--msvs_version=2013`. 

Are both installed?
If yes, what version of python is used `python --version`

**Comment by canfoderiskii** [comment]
@MatthiasF999  is the visual studio 2013 you mentioned actually visual c++ 2013 runtime library? do i have to install the whole visual studio 2013?
About python, i am using python 3.5

**Comment by canfoderiskii** [comment]
@MatthiasF999 Ok, i digged some infomation. It seems i have to install the whole package of visual studio. Is the community version of vs2013 able to make node-gyp work?

**Comment by canfoderiskii** [comment]
Problem solved!
In general, I have to install python 2.7, visual studio 2013 and python module gyp.

@MichaelIT maybe u can see the node-gyp installation document as a reference for compiler selection on Mac OS X.

@MatthiasF999 Thanks for your reply, it really helps a lot.
