### ISSUE TITLE
Package Installation

### ISSUE THREAD

**Issue by stamariajerome** [Floobits/atom-term3#59]
Installing term3 to C:\Users\Jerome Sta. Maria\.atom\packages failed

ptyw.js@0.3.8 install C:\Users\JEROME~1.MAR\AppData\Local\Temp\apm-install-dir-116417-2724-11vry7u\node_modules\term3\node_modules\ptyw.js
node-gyp rebuild

C:\Users\JEROME~1.MAR\AppData\Local\Temp\apm-install-dir-116417-2724-11vry7u\node_modules\term3\node_modules\ptyw.js>if not defined npm_config_node_gyp (node "C:\Users\Jerome Sta. Maria\AppData\Local\atom\app-1.7.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
gypnpm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Jerome Sta. Maria\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Jerome Sta. Maria\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Jerome Sta. Maria\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Jerome Sta. Maria\\.atom\\.apmrc" "install" "C:\\Users\\JEROME~1.MAR\\AppData\\Local\\Temp\\d-116417-2724-eahpkq\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.3.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ptyw.js@0.3.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.`

**Comment by stamariajerome** [comment]
Anyone know why I'm having this error when I try to install term3 via cli.

**Comment by wenmm** [comment]
did you fill this problem yet? i came across the same problem as yours ,i have installed graceful-fs @4+, and react-tools deprecated, what can i do???
