### ISSUE TITLE
Using this or atom-term2

### ISSUE THREAD

**Issue by chamini2** [Floobits/atom-term3#6]
In [this pull request](https://github.com/f/atom-term2/pull/194#issuecomment-145453268) @kans states that he intends to shut down atom-term3, should we just stick to atom-term2 and wait for this to happen?

**Comment by ywecur** [comment]
+1

Would really like this clarified

**Comment by kans** [comment]
There are quite a few fixes in term3, but most of the work is adding support for the Floobits plugin.

**Comment by chamini2** [comment]
Are you making a pull request for the few fixes?
